### ISSUE TITLE
document release process

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-js#21]
This thing is published on npm now as `replicate`! That's awesome.

@erbridge what's your release process been so far?

Followup to https://github.com/replicate/replicate-js/issues/5

**Comment by zeke** [comment]
I assume you're just doing manual publishes for now, but we have a `replicatebot` npm account we can use for this when the time is right: https://github.com/replicate/openapi/pull/2#issuecomment-1402870152

**Comment by erbridge** [comment]
I've been using `npx np minor` for now.

**Comment by zeke** [comment]
https://github.com/replicate/replicate-js/releases/tag/v0.5.0
